### PR TITLE
Expand PX121 specification, Ship and ShipState for fuel consumption simulation

### PR DESCRIPTION
**Pull request by icarofonseca**
* Create `shipState` inside `designStates` to handle states which are related to the vessel as a whole, and not to its individual `derivedObjects`.
* Collect relevant ship definitions under `calculationParameters`.
* Allow one to specify a tank as fuel tank.
* Implement functions to return fuel amount and to subtract consumed fuel mass from tanks.
* Introduce simple propeller and power plant specification libraries.
Note: I didn't modify methods `calculateStability`, `calculateDraftWeigthBased` and `calculateDraftIterationBased`, just rearranged their layout and changed indentation from spaces to tabs, for consistency.

### CODE REVIEW

**Comment by EliasHasle** [comment]
This sounds great! I will look at it later. :-)

8. mar. 2018 23.33 skrev "Ícaro Fonseca" <notifications@github.com>:

**Comment by EliasHasle** [comment]
OK, now I had a look at this PR. It looks good. For the examples, I think you know much better than me what you are doing. The modifications to the common code are very modest. I am a bit uncertain about some, though.

Fuel tank could be an object group rather than a capability. Have you considered that option? I would think that is a typical use of groups. If the groups are not suited for that, maybe they aren't suited for anything.

I will take the discussions on ship state and caching in #41.

If this PR doesn't break any examples, I think it can be merged. I wouldn't say it is really ready yet, but that applies to some of the code in master too. Not that it is something we should just accept, but right now it could be a good idea for collaboration to just get the versions synced. Then we fix the problems.

**Comment by icarofonseca** [comment]
Ok, I am implementing your suggestions now. So a group should be defined like: 
```js 
ship.baseObjects["TankL10.5B3H5.3fdundefinedFtank11.stl"].group = "fuelTanks"
```
Is this right?

**Comment by icarofonseca** [comment]
Actually, this kind of characterization could be handled by the SFI **group** system, but I don't have a SFI description with me now to know what code goes for fuel tanks. I'll check that later.

**Pull request merged**
